package com.example.fullthrottle.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFAC3500)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBD0)
val md_theme_light_onPrimaryContainer = Color(0xFF390C00)
val md_theme_light_secondary = Color(0xFF3A6A1D)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFBAF295)
val md_theme_light_onSecondaryContainer = Color(0xFF092100)
val md_theme_light_tertiary = Color(0xFF0561A4)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD2E4FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001D36)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A18)
val md_theme_light_outline = Color(0xFF85736E)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEEA)
val md_theme_light_inverseSurface = Color(0xFF362F2D)
val md_theme_light_inversePrimary = Color(0xFFFFB59D)
val md_theme_light_surfaceTint = Color(0xFFAC3500)
val md_theme_light_outlineVariant = Color(0xFFD8C2BB)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFFF8F6)
val md_theme_light_onSurface = Color(0xFF201A18)
val md_theme_light_surfaceVariant = Color(0xFFF5DED7)
val md_theme_light_onSurfaceVariant = Color(0xFF53433F)

val md_theme_dark_primary = Color(0xFFFFB59D)
val md_theme_dark_onPrimary = Color(0xFF5D1800)
val md_theme_dark_primaryContainer = Color(0xFF832600)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBD0)
val md_theme_dark_secondary = Color(0xFF9FD67B)
val md_theme_dark_onSecondary = Color(0xFF153800)
val md_theme_dark_secondaryContainer = Color(0xFF235104)
val md_theme_dark_onSecondaryContainer = Color(0xFFBAF295)
val md_theme_dark_tertiary = Color(0xFF9FCAFF)
val md_theme_dark_onTertiary = Color(0xFF003259)
val md_theme_dark_tertiaryContainer = Color(0xFF00497E)
val md_theme_dark_onTertiaryContainer = Color(0xFFD2E4FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF141414)//Color(0xFF201A18)
val md_theme_dark_onBackground = Color(0xFFEDE0DC)
val md_theme_dark_outline = Color(0xFFA08D87)
val md_theme_dark_inverseOnSurface = Color(0xFF201A18)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DC)
val md_theme_dark_inversePrimary = Color(0xFFAC3500)
val md_theme_dark_surfaceTint = Color(0xFFFFB59D)
val md_theme_dark_outlineVariant = Color(0xFF53433F)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF181210)
val md_theme_dark_onSurface = Color(0xFFD0C4C1)
val md_theme_dark_surfaceVariant = Color(0xFF403030)//Color(0xFF53433F)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BB)


val seed = Color(0xFFEF510E)
